packages:
  - ./newIndexer
  - ./hayooFrontend
  - ./hayooLib
  - ../hunt/hunt-client
  - ../hunt/hunt-crawler
  - ../hunt/hunt-searchengine  
  - ./hayooIndexer
extra-deps:
  - data-r-tree-0.0.5.0
  - data-stringmap-1.0.1.1
  - murmur-hash-0.1.0.8
  - hxt-xpath-9.1.2.2
  - hxt-cache-9.1.0.1
resolver: lts-2.15

